name: ditonton
description: A new Flutter application.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cached_network_image: ^3.0.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0-nullsafety.2
  equatable: ^2.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_rating_bar: ^4.0.0
  get_it: ^7.1.3
  google_fonts: ^5.1.0
  http: ^1.1.0
  path_provider: ^2.0.2
  provider: ^6.0.3
  rxdart: ^0.27.7
  sqflite: ^2.0.0+3

dev_dependencies:
  analyzer: 5.13.0
  bloc_test: ^9.1.5
  build_runner: ^2.0.4
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  mockito: ^5.4.3
  mocktail: ^1.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
