// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKPbm2wlyKADIUrVdr3K13-TdJgTALI50',
    appId: '1:1028957913351:web:a62a40b29f7e87c1b045a2',
    messagingSenderId: '1028957913351',
    projectId: 'fam-flutter-expert-project',
    authDomain: 'fam-flutter-expert-project.firebaseapp.com',
    storageBucket: 'fam-flutter-expert-project.appspot.com',
    measurementId: 'G-RNTEX9BW28',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0JVfGv-Vkp2G1XplPNatqkHAAQOZM0wU',
    appId: '1:1028957913351:android:723ba8f246442e71b045a2',
    messagingSenderId: '1028957913351',
    projectId: 'fam-flutter-expert-project',
    storageBucket: 'fam-flutter-expert-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC5o9mgAh51ENCLHjTJU9zOeZcZXlQZK8',
    appId: '1:1028957913351:ios:15a97bcd37a0853ab045a2',
    messagingSenderId: '1028957913351',
    projectId: 'fam-flutter-expert-project',
    storageBucket: 'fam-flutter-expert-project.appspot.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
