// Mocks generated by Mockito 5.4.3 from annotations
// in ditonton/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:convert' as _i25;
import 'dart:typed_data' as _i26;

import 'package:dartz/dartz.dart' as _i2;
import 'package:ditonton/common/failure.dart' as _i8;
import 'package:ditonton/data/datasources/db/database_helper.dart' as _i19;
import 'package:ditonton/data/datasources/movie_remote_data_source.dart'
    as _i11;
import 'package:ditonton/data/datasources/tv_remote_data_source.dart' as _i21;
import 'package:ditonton/data/datasources/watchlist_local_data_source.dart'
    as _i13;
import 'package:ditonton/data/models/movie_detail_model.dart' as _i3;
import 'package:ditonton/data/models/movie_model.dart' as _i12;
import 'package:ditonton/data/models/tv_detail_response_model.dart' as _i4;
import 'package:ditonton/data/models/tv_series_response_model.dart' as _i22;
import 'package:ditonton/data/models/watchlist_table.dart' as _i14;
import 'package:ditonton/domain/entities/item_data_entity.dart' as _i17;
import 'package:ditonton/domain/entities/movie_detail_entity.dart' as _i10;
import 'package:ditonton/domain/entities/movie_entity.dart' as _i9;
import 'package:ditonton/domain/entities/poster_5_entity.dart' as _i18;
import 'package:ditonton/domain/entities/tvseries_entity.dart' as _i24;
import 'package:ditonton/domain/repositories/movie_repository.dart' as _i6;
import 'package:ditonton/domain/repositories/tv_series_repository.dart' as _i23;
import 'package:ditonton/domain/repositories/watch_list_repository.dart'
    as _i16;
import 'package:http/http.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i15;
import 'package:sqflite/sqflite.dart' as _i20;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMovieDetailResponse_1 extends _i1.SmartFake
    implements _i3.MovieDetailResponse {
  _FakeMovieDetailResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTvDetailResponseModel_2 extends _i1.SmartFake
    implements _i4.TvDetailResponseModel {
  _FakeTvDetailResponseModel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_3 extends _i1.SmartFake implements _i5.Response {
  _FakeResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamedResponse_4 extends _i1.SmartFake
    implements _i5.StreamedResponse {
  _FakeStreamedResponse_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MovieRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRepository extends _i1.Mock implements _i6.MovieRepository {
  MockMovieRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i9.MovieEntity>>>
      getNowPlayingMovies() => (super.noSuchMethod(
            Invocation.method(
              #getNowPlayingMovies,
              [],
            ),
            returnValue: _i7
                .Future<_i2.Either<_i8.Failure, List<_i9.MovieEntity>>>.value(
                _FakeEither_0<_i8.Failure, List<_i9.MovieEntity>>(
              this,
              Invocation.method(
                #getNowPlayingMovies,
                [],
              ),
            )),
          ) as _i7.Future<_i2.Either<_i8.Failure, List<_i9.MovieEntity>>>);

  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i9.MovieEntity>>>
      getPopularMovies() => (super.noSuchMethod(
            Invocation.method(
              #getPopularMovies,
              [],
            ),
            returnValue: _i7
                .Future<_i2.Either<_i8.Failure, List<_i9.MovieEntity>>>.value(
                _FakeEither_0<_i8.Failure, List<_i9.MovieEntity>>(
              this,
              Invocation.method(
                #getPopularMovies,
                [],
              ),
            )),
          ) as _i7.Future<_i2.Either<_i8.Failure, List<_i9.MovieEntity>>>);

  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i9.MovieEntity>>>
      getTopRatedMovies() => (super.noSuchMethod(
            Invocation.method(
              #getTopRatedMovies,
              [],
            ),
            returnValue: _i7
                .Future<_i2.Either<_i8.Failure, List<_i9.MovieEntity>>>.value(
                _FakeEither_0<_i8.Failure, List<_i9.MovieEntity>>(
              this,
              Invocation.method(
                #getTopRatedMovies,
                [],
              ),
            )),
          ) as _i7.Future<_i2.Either<_i8.Failure, List<_i9.MovieEntity>>>);

  @override
  _i7.Future<_i2.Either<_i8.Failure, _i10.MovieDetailEntity>> getMovieDetail(
          int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieDetail,
          [id],
        ),
        returnValue:
            _i7.Future<_i2.Either<_i8.Failure, _i10.MovieDetailEntity>>.value(
                _FakeEither_0<_i8.Failure, _i10.MovieDetailEntity>(
          this,
          Invocation.method(
            #getMovieDetail,
            [id],
          ),
        )),
      ) as _i7.Future<_i2.Either<_i8.Failure, _i10.MovieDetailEntity>>);

  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i9.MovieEntity>>>
      getMovieRecommendations(int? id) => (super.noSuchMethod(
            Invocation.method(
              #getMovieRecommendations,
              [id],
            ),
            returnValue: _i7
                .Future<_i2.Either<_i8.Failure, List<_i9.MovieEntity>>>.value(
                _FakeEither_0<_i8.Failure, List<_i9.MovieEntity>>(
              this,
              Invocation.method(
                #getMovieRecommendations,
                [id],
              ),
            )),
          ) as _i7.Future<_i2.Either<_i8.Failure, List<_i9.MovieEntity>>>);

  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i9.MovieEntity>>> searchMovies(
          String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchMovies,
          [query],
        ),
        returnValue:
            _i7.Future<_i2.Either<_i8.Failure, List<_i9.MovieEntity>>>.value(
                _FakeEither_0<_i8.Failure, List<_i9.MovieEntity>>(
          this,
          Invocation.method(
            #searchMovies,
            [query],
          ),
        )),
      ) as _i7.Future<_i2.Either<_i8.Failure, List<_i9.MovieEntity>>>);
}

/// A class which mocks [MovieRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRemoteDataSource extends _i1.Mock
    implements _i11.MovieRemoteDataSource {
  MockMovieRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i12.MovieModel>> getNowPlayingMovies() =>
      (super.noSuchMethod(
        Invocation.method(
          #getNowPlayingMovies,
          [],
        ),
        returnValue:
            _i7.Future<List<_i12.MovieModel>>.value(<_i12.MovieModel>[]),
      ) as _i7.Future<List<_i12.MovieModel>>);

  @override
  _i7.Future<List<_i12.MovieModel>> getPopularMovies() => (super.noSuchMethod(
        Invocation.method(
          #getPopularMovies,
          [],
        ),
        returnValue:
            _i7.Future<List<_i12.MovieModel>>.value(<_i12.MovieModel>[]),
      ) as _i7.Future<List<_i12.MovieModel>>);

  @override
  _i7.Future<List<_i12.MovieModel>> getTopRatedMovies() => (super.noSuchMethod(
        Invocation.method(
          #getTopRatedMovies,
          [],
        ),
        returnValue:
            _i7.Future<List<_i12.MovieModel>>.value(<_i12.MovieModel>[]),
      ) as _i7.Future<List<_i12.MovieModel>>);

  @override
  _i7.Future<_i3.MovieDetailResponse> getMovieDetail(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieDetail,
          [id],
        ),
        returnValue: _i7.Future<_i3.MovieDetailResponse>.value(
            _FakeMovieDetailResponse_1(
          this,
          Invocation.method(
            #getMovieDetail,
            [id],
          ),
        )),
      ) as _i7.Future<_i3.MovieDetailResponse>);

  @override
  _i7.Future<List<_i12.MovieModel>> getMovieRecommendations(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieRecommendations,
          [id],
        ),
        returnValue:
            _i7.Future<List<_i12.MovieModel>>.value(<_i12.MovieModel>[]),
      ) as _i7.Future<List<_i12.MovieModel>>);

  @override
  _i7.Future<List<_i12.MovieModel>> searchMovies(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchMovies,
          [query],
        ),
        returnValue:
            _i7.Future<List<_i12.MovieModel>>.value(<_i12.MovieModel>[]),
      ) as _i7.Future<List<_i12.MovieModel>>);
}

/// A class which mocks [WatchlistLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchlistLocalDataSource extends _i1.Mock
    implements _i13.WatchlistLocalDataSource {
  MockWatchlistLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<String> insertWatchlist(_i14.WatchlistTable? movie) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertWatchlist,
          [movie],
        ),
        returnValue: _i7.Future<String>.value(_i15.dummyValue<String>(
          this,
          Invocation.method(
            #insertWatchlist,
            [movie],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<String> removeWatchlist(
    int? id,
    int? dataType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeWatchlist,
          [
            id,
            dataType,
          ],
        ),
        returnValue: _i7.Future<String>.value(_i15.dummyValue<String>(
          this,
          Invocation.method(
            #removeWatchlist,
            [
              id,
              dataType,
            ],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<_i14.WatchlistTable?> getMovieById(
    int? id,
    int? dataType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieById,
          [
            id,
            dataType,
          ],
        ),
        returnValue: _i7.Future<_i14.WatchlistTable?>.value(),
      ) as _i7.Future<_i14.WatchlistTable?>);

  @override
  _i7.Future<List<_i14.WatchlistTable>> getWatchlistMovies() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWatchlistMovies,
          [],
        ),
        returnValue: _i7.Future<List<_i14.WatchlistTable>>.value(
            <_i14.WatchlistTable>[]),
      ) as _i7.Future<List<_i14.WatchlistTable>>);
}

/// A class which mocks [WatchlistRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchlistRepository extends _i1.Mock
    implements _i16.WatchlistRepository {
  MockWatchlistRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.Either<_i8.Failure, String>> saveWatchlist(
          _i17.ItemDataEntity? itemDataEntity) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveWatchlist,
          [itemDataEntity],
        ),
        returnValue: _i7.Future<_i2.Either<_i8.Failure, String>>.value(
            _FakeEither_0<_i8.Failure, String>(
          this,
          Invocation.method(
            #saveWatchlist,
            [itemDataEntity],
          ),
        )),
      ) as _i7.Future<_i2.Either<_i8.Failure, String>>);

  @override
  _i7.Future<_i2.Either<_i8.Failure, String>> removeWatchlist(
    int? id,
    int? dataType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeWatchlist,
          [
            id,
            dataType,
          ],
        ),
        returnValue: _i7.Future<_i2.Either<_i8.Failure, String>>.value(
            _FakeEither_0<_i8.Failure, String>(
          this,
          Invocation.method(
            #removeWatchlist,
            [
              id,
              dataType,
            ],
          ),
        )),
      ) as _i7.Future<_i2.Either<_i8.Failure, String>>);

  @override
  _i7.Future<bool> isAddedToWatchlist(
    int? id,
    int? dataType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isAddedToWatchlist,
          [
            id,
            dataType,
          ],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i18.Poster5Entity>>>
      getWatchlist() => (super.noSuchMethod(
            Invocation.method(
              #getWatchlist,
              [],
            ),
            returnValue: _i7.Future<
                    _i2.Either<_i8.Failure, List<_i18.Poster5Entity>>>.value(
                _FakeEither_0<_i8.Failure, List<_i18.Poster5Entity>>(
              this,
              Invocation.method(
                #getWatchlist,
                [],
              ),
            )),
          ) as _i7.Future<_i2.Either<_i8.Failure, List<_i18.Poster5Entity>>>);
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i19.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i20.Database?> get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _i7.Future<_i20.Database?>.value(),
      ) as _i7.Future<_i20.Database?>);

  @override
  _i7.Future<int> insertWatchlist(_i14.WatchlistTable? movie) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertWatchlist,
          [movie],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<int> removeWatchlist(
    int? id,
    int? dataType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeWatchlist,
          [
            id,
            dataType,
          ],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<Map<String, dynamic>?> getMovieById(
    int? id,
    int? dataType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieById,
          [
            id,
            dataType,
          ],
        ),
        returnValue: _i7.Future<Map<String, dynamic>?>.value(),
      ) as _i7.Future<Map<String, dynamic>?>);

  @override
  _i7.Future<List<Map<String, dynamic>>> getWatchlistMovies() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWatchlistMovies,
          [],
        ),
        returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i7.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [TvRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvRemoteDataSource extends _i1.Mock
    implements _i21.TvRemoteDataSource {
  MockTvRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i22.ResultTvSeries>> getPopularTvSeries() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPopularTvSeries,
          [],
        ),
        returnValue: _i7.Future<List<_i22.ResultTvSeries>>.value(
            <_i22.ResultTvSeries>[]),
      ) as _i7.Future<List<_i22.ResultTvSeries>>);

  @override
  _i7.Future<List<_i22.ResultTvSeries>> getOnTheAirTvSeries() =>
      (super.noSuchMethod(
        Invocation.method(
          #getOnTheAirTvSeries,
          [],
        ),
        returnValue: _i7.Future<List<_i22.ResultTvSeries>>.value(
            <_i22.ResultTvSeries>[]),
      ) as _i7.Future<List<_i22.ResultTvSeries>>);

  @override
  _i7.Future<List<_i22.ResultTvSeries>> getTopRatedTvSeries() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopRatedTvSeries,
          [],
        ),
        returnValue: _i7.Future<List<_i22.ResultTvSeries>>.value(
            <_i22.ResultTvSeries>[]),
      ) as _i7.Future<List<_i22.ResultTvSeries>>);

  @override
  _i7.Future<List<_i22.ResultTvSeries>> searchTvSeries(String? keyword) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchTvSeries,
          [keyword],
        ),
        returnValue: _i7.Future<List<_i22.ResultTvSeries>>.value(
            <_i22.ResultTvSeries>[]),
      ) as _i7.Future<List<_i22.ResultTvSeries>>);

  @override
  _i7.Future<_i4.TvDetailResponseModel> getTvSeriesDetail(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvSeriesDetail,
          [id],
        ),
        returnValue: _i7.Future<_i4.TvDetailResponseModel>.value(
            _FakeTvDetailResponseModel_2(
          this,
          Invocation.method(
            #getTvSeriesDetail,
            [id],
          ),
        )),
      ) as _i7.Future<_i4.TvDetailResponseModel>);

  @override
  _i7.Future<List<_i22.ResultTvSeries>> getTvSeriesRecommendation(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvSeriesRecommendation,
          [id],
        ),
        returnValue: _i7.Future<List<_i22.ResultTvSeries>>.value(
            <_i22.ResultTvSeries>[]),
      ) as _i7.Future<List<_i22.ResultTvSeries>>);
}

/// A class which mocks [TvSeriesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesRepository extends _i1.Mock
    implements _i23.TvSeriesRepository {
  MockTvSeriesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i24.TvSeriesEntity>>>
      getOnTheAirTvSeries() => (super.noSuchMethod(
            Invocation.method(
              #getOnTheAirTvSeries,
              [],
            ),
            returnValue: _i7.Future<
                    _i2.Either<_i8.Failure, List<_i24.TvSeriesEntity>>>.value(
                _FakeEither_0<_i8.Failure, List<_i24.TvSeriesEntity>>(
              this,
              Invocation.method(
                #getOnTheAirTvSeries,
                [],
              ),
            )),
          ) as _i7.Future<_i2.Either<_i8.Failure, List<_i24.TvSeriesEntity>>>);

  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i24.TvSeriesEntity>>>
      getPopularTvSeries() => (super.noSuchMethod(
            Invocation.method(
              #getPopularTvSeries,
              [],
            ),
            returnValue: _i7.Future<
                    _i2.Either<_i8.Failure, List<_i24.TvSeriesEntity>>>.value(
                _FakeEither_0<_i8.Failure, List<_i24.TvSeriesEntity>>(
              this,
              Invocation.method(
                #getPopularTvSeries,
                [],
              ),
            )),
          ) as _i7.Future<_i2.Either<_i8.Failure, List<_i24.TvSeriesEntity>>>);

  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i24.TvSeriesEntity>>>
      getTopRatedTvSeries() => (super.noSuchMethod(
            Invocation.method(
              #getTopRatedTvSeries,
              [],
            ),
            returnValue: _i7.Future<
                    _i2.Either<_i8.Failure, List<_i24.TvSeriesEntity>>>.value(
                _FakeEither_0<_i8.Failure, List<_i24.TvSeriesEntity>>(
              this,
              Invocation.method(
                #getTopRatedTvSeries,
                [],
              ),
            )),
          ) as _i7.Future<_i2.Either<_i8.Failure, List<_i24.TvSeriesEntity>>>);

  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i24.TvSeriesEntity>>> searchTvSeries(
          String? keyword) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchTvSeries,
          [keyword],
        ),
        returnValue: _i7
            .Future<_i2.Either<_i8.Failure, List<_i24.TvSeriesEntity>>>.value(
            _FakeEither_0<_i8.Failure, List<_i24.TvSeriesEntity>>(
          this,
          Invocation.method(
            #searchTvSeries,
            [keyword],
          ),
        )),
      ) as _i7.Future<_i2.Either<_i8.Failure, List<_i24.TvSeriesEntity>>>);

  @override
  _i7.Future<_i2.Either<_i8.Failure, _i17.ItemDataEntity>> getTvSeriesDetail(
          int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvSeriesDetail,
          [id],
        ),
        returnValue:
            _i7.Future<_i2.Either<_i8.Failure, _i17.ItemDataEntity>>.value(
                _FakeEither_0<_i8.Failure, _i17.ItemDataEntity>(
          this,
          Invocation.method(
            #getTvSeriesDetail,
            [id],
          ),
        )),
      ) as _i7.Future<_i2.Either<_i8.Failure, _i17.ItemDataEntity>>);

  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i24.TvSeriesEntity>>>
      getTvSeriesRecommendation(int? id) => (super.noSuchMethod(
            Invocation.method(
              #getTvSeriesRecommendation,
              [id],
            ),
            returnValue: _i7.Future<
                    _i2.Either<_i8.Failure, List<_i24.TvSeriesEntity>>>.value(
                _FakeEither_0<_i8.Failure, List<_i24.TvSeriesEntity>>(
              this,
              Invocation.method(
                #getTvSeriesRecommendation,
                [id],
              ),
            )),
          ) as _i7.Future<_i2.Either<_i8.Failure, List<_i24.TvSeriesEntity>>>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i5.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i5.Response> head(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [url],
          {#headers: headers},
        ),
        returnValue: _i7.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #head,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i7.Future<_i5.Response>);

  @override
  _i7.Future<_i5.Response> get(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {#headers: headers},
        ),
        returnValue: _i7.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i7.Future<_i5.Response>);

  @override
  _i7.Future<_i5.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i25.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i7.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i7.Future<_i5.Response>);

  @override
  _i7.Future<_i5.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i25.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i7.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i7.Future<_i5.Response>);

  @override
  _i7.Future<_i5.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i25.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i7.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i7.Future<_i5.Response>);

  @override
  _i7.Future<_i5.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i25.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i7.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i7.Future<_i5.Response>);

  @override
  _i7.Future<String> read(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [url],
          {#headers: headers},
        ),
        returnValue: _i7.Future<String>.value(_i15.dummyValue<String>(
          this,
          Invocation.method(
            #read,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<_i26.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readBytes,
          [url],
          {#headers: headers},
        ),
        returnValue: _i7.Future<_i26.Uint8List>.value(_i26.Uint8List(0)),
      ) as _i7.Future<_i26.Uint8List>);

  @override
  _i7.Future<_i5.StreamedResponse> send(_i5.BaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [request],
        ),
        returnValue:
            _i7.Future<_i5.StreamedResponse>.value(_FakeStreamedResponse_4(
          this,
          Invocation.method(
            #send,
            [request],
          ),
        )),
      ) as _i7.Future<_i5.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
