// Mocks generated by Mockito 5.4.3 from annotations
// in ditonton/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;
import 'dart:io' as _i6;

import 'package:dartz/dartz.dart' as _i2;
import 'package:ditonton/common/failure.dart' as _i10;
import 'package:ditonton/common/firebase_analytics_service.dart' as _i27;
import 'package:ditonton/common/http_custom_client.dart' as _i28;
import 'package:ditonton/data/datasources/db/database_helper.dart' as _i21;
import 'package:ditonton/data/datasources/movie_remote_data_source.dart'
    as _i13;
import 'package:ditonton/data/datasources/tv_remote_data_source.dart' as _i23;
import 'package:ditonton/data/datasources/watchlist_local_data_source.dart'
    as _i15;
import 'package:ditonton/data/models/movie_detail_model.dart' as _i3;
import 'package:ditonton/data/models/movie_model.dart' as _i14;
import 'package:ditonton/data/models/tv_detail_response_model.dart' as _i4;
import 'package:ditonton/data/models/tv_series_response_model.dart' as _i24;
import 'package:ditonton/data/models/watchlist_table.dart' as _i16;
import 'package:ditonton/domain/entities/item_data_entity.dart' as _i19;
import 'package:ditonton/domain/entities/movie_detail_entity.dart' as _i12;
import 'package:ditonton/domain/entities/movie_entity.dart' as _i11;
import 'package:ditonton/domain/entities/poster_5_entity.dart' as _i20;
import 'package:ditonton/domain/entities/tvseries_entity.dart' as _i26;
import 'package:ditonton/domain/repositories/movie_repository.dart' as _i8;
import 'package:ditonton/domain/repositories/tv_series_repository.dart' as _i25;
import 'package:ditonton/domain/repositories/watch_list_repository.dart'
    as _i18;
import 'package:firebase_analytics/firebase_analytics.dart' as _i5;
import 'package:http/http.dart' as _i7;
import 'package:http/io_client.dart' as _i29;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i17;
import 'package:sqflite/sqflite.dart' as _i22;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMovieDetailResponse_1 extends _i1.SmartFake
    implements _i3.MovieDetailResponse {
  _FakeMovieDetailResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTvDetailResponseModel_2 extends _i1.SmartFake
    implements _i4.TvDetailResponseModel {
  _FakeTvDetailResponseModel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFirebaseAnalytics_3 extends _i1.SmartFake
    implements _i5.FirebaseAnalytics {
  _FakeFirebaseAnalytics_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFirebaseAnalyticsObserver_4 extends _i1.SmartFake
    implements _i5.FirebaseAnalyticsObserver {
  _FakeFirebaseAnalyticsObserver_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAnalyticsEventItem_5 extends _i1.SmartFake
    implements _i5.AnalyticsEventItem {
  _FakeAnalyticsEventItem_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSecurityContext_6 extends _i1.SmartFake
    implements _i6.SecurityContext {
  _FakeSecurityContext_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_7 extends _i1.SmartFake implements _i7.Response {
  _FakeResponse_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MovieRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRepository extends _i1.Mock implements _i8.MovieRepository {
  MockMovieRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i2.Either<_i10.Failure, List<_i11.MovieEntity>>>
      getNowPlayingMovies() => (super.noSuchMethod(
            Invocation.method(
              #getNowPlayingMovies,
              [],
            ),
            returnValue: _i9
                .Future<_i2.Either<_i10.Failure, List<_i11.MovieEntity>>>.value(
                _FakeEither_0<_i10.Failure, List<_i11.MovieEntity>>(
              this,
              Invocation.method(
                #getNowPlayingMovies,
                [],
              ),
            )),
          ) as _i9.Future<_i2.Either<_i10.Failure, List<_i11.MovieEntity>>>);

  @override
  _i9.Future<_i2.Either<_i10.Failure, List<_i11.MovieEntity>>>
      getPopularMovies() => (super.noSuchMethod(
            Invocation.method(
              #getPopularMovies,
              [],
            ),
            returnValue: _i9
                .Future<_i2.Either<_i10.Failure, List<_i11.MovieEntity>>>.value(
                _FakeEither_0<_i10.Failure, List<_i11.MovieEntity>>(
              this,
              Invocation.method(
                #getPopularMovies,
                [],
              ),
            )),
          ) as _i9.Future<_i2.Either<_i10.Failure, List<_i11.MovieEntity>>>);

  @override
  _i9.Future<_i2.Either<_i10.Failure, List<_i11.MovieEntity>>>
      getTopRatedMovies() => (super.noSuchMethod(
            Invocation.method(
              #getTopRatedMovies,
              [],
            ),
            returnValue: _i9
                .Future<_i2.Either<_i10.Failure, List<_i11.MovieEntity>>>.value(
                _FakeEither_0<_i10.Failure, List<_i11.MovieEntity>>(
              this,
              Invocation.method(
                #getTopRatedMovies,
                [],
              ),
            )),
          ) as _i9.Future<_i2.Either<_i10.Failure, List<_i11.MovieEntity>>>);

  @override
  _i9.Future<_i2.Either<_i10.Failure, _i12.MovieDetailEntity>> getMovieDetail(
          int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieDetail,
          [id],
        ),
        returnValue:
            _i9.Future<_i2.Either<_i10.Failure, _i12.MovieDetailEntity>>.value(
                _FakeEither_0<_i10.Failure, _i12.MovieDetailEntity>(
          this,
          Invocation.method(
            #getMovieDetail,
            [id],
          ),
        )),
      ) as _i9.Future<_i2.Either<_i10.Failure, _i12.MovieDetailEntity>>);

  @override
  _i9.Future<_i2.Either<_i10.Failure, List<_i11.MovieEntity>>>
      getMovieRecommendations(int? id) => (super.noSuchMethod(
            Invocation.method(
              #getMovieRecommendations,
              [id],
            ),
            returnValue: _i9
                .Future<_i2.Either<_i10.Failure, List<_i11.MovieEntity>>>.value(
                _FakeEither_0<_i10.Failure, List<_i11.MovieEntity>>(
              this,
              Invocation.method(
                #getMovieRecommendations,
                [id],
              ),
            )),
          ) as _i9.Future<_i2.Either<_i10.Failure, List<_i11.MovieEntity>>>);

  @override
  _i9.Future<_i2.Either<_i10.Failure, List<_i11.MovieEntity>>> searchMovies(
          String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchMovies,
          [query],
        ),
        returnValue:
            _i9.Future<_i2.Either<_i10.Failure, List<_i11.MovieEntity>>>.value(
                _FakeEither_0<_i10.Failure, List<_i11.MovieEntity>>(
          this,
          Invocation.method(
            #searchMovies,
            [query],
          ),
        )),
      ) as _i9.Future<_i2.Either<_i10.Failure, List<_i11.MovieEntity>>>);
}

/// A class which mocks [MovieRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRemoteDataSource extends _i1.Mock
    implements _i13.MovieRemoteDataSource {
  MockMovieRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<List<_i14.MovieModel>> getNowPlayingMovies() =>
      (super.noSuchMethod(
        Invocation.method(
          #getNowPlayingMovies,
          [],
        ),
        returnValue:
            _i9.Future<List<_i14.MovieModel>>.value(<_i14.MovieModel>[]),
      ) as _i9.Future<List<_i14.MovieModel>>);

  @override
  _i9.Future<List<_i14.MovieModel>> getPopularMovies() => (super.noSuchMethod(
        Invocation.method(
          #getPopularMovies,
          [],
        ),
        returnValue:
            _i9.Future<List<_i14.MovieModel>>.value(<_i14.MovieModel>[]),
      ) as _i9.Future<List<_i14.MovieModel>>);

  @override
  _i9.Future<List<_i14.MovieModel>> getTopRatedMovies() => (super.noSuchMethod(
        Invocation.method(
          #getTopRatedMovies,
          [],
        ),
        returnValue:
            _i9.Future<List<_i14.MovieModel>>.value(<_i14.MovieModel>[]),
      ) as _i9.Future<List<_i14.MovieModel>>);

  @override
  _i9.Future<_i3.MovieDetailResponse> getMovieDetail(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieDetail,
          [id],
        ),
        returnValue: _i9.Future<_i3.MovieDetailResponse>.value(
            _FakeMovieDetailResponse_1(
          this,
          Invocation.method(
            #getMovieDetail,
            [id],
          ),
        )),
      ) as _i9.Future<_i3.MovieDetailResponse>);

  @override
  _i9.Future<List<_i14.MovieModel>> getMovieRecommendations(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieRecommendations,
          [id],
        ),
        returnValue:
            _i9.Future<List<_i14.MovieModel>>.value(<_i14.MovieModel>[]),
      ) as _i9.Future<List<_i14.MovieModel>>);

  @override
  _i9.Future<List<_i14.MovieModel>> searchMovies(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchMovies,
          [query],
        ),
        returnValue:
            _i9.Future<List<_i14.MovieModel>>.value(<_i14.MovieModel>[]),
      ) as _i9.Future<List<_i14.MovieModel>>);
}

/// A class which mocks [WatchlistLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchlistLocalDataSource extends _i1.Mock
    implements _i15.WatchlistLocalDataSource {
  MockWatchlistLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<String> insertWatchlist(_i16.WatchlistTable? movie) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertWatchlist,
          [movie],
        ),
        returnValue: _i9.Future<String>.value(_i17.dummyValue<String>(
          this,
          Invocation.method(
            #insertWatchlist,
            [movie],
          ),
        )),
      ) as _i9.Future<String>);

  @override
  _i9.Future<String> removeWatchlist(
    int? id,
    int? dataType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeWatchlist,
          [
            id,
            dataType,
          ],
        ),
        returnValue: _i9.Future<String>.value(_i17.dummyValue<String>(
          this,
          Invocation.method(
            #removeWatchlist,
            [
              id,
              dataType,
            ],
          ),
        )),
      ) as _i9.Future<String>);

  @override
  _i9.Future<_i16.WatchlistTable?> getMovieById(
    int? id,
    int? dataType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieById,
          [
            id,
            dataType,
          ],
        ),
        returnValue: _i9.Future<_i16.WatchlistTable?>.value(),
      ) as _i9.Future<_i16.WatchlistTable?>);

  @override
  _i9.Future<List<_i16.WatchlistTable>> getWatchlistMovies() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWatchlistMovies,
          [],
        ),
        returnValue: _i9.Future<List<_i16.WatchlistTable>>.value(
            <_i16.WatchlistTable>[]),
      ) as _i9.Future<List<_i16.WatchlistTable>>);
}

/// A class which mocks [WatchlistRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchlistRepository extends _i1.Mock
    implements _i18.WatchlistRepository {
  MockWatchlistRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i2.Either<_i10.Failure, String>> saveWatchlist(
          _i19.ItemDataEntity? itemDataEntity) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveWatchlist,
          [itemDataEntity],
        ),
        returnValue: _i9.Future<_i2.Either<_i10.Failure, String>>.value(
            _FakeEither_0<_i10.Failure, String>(
          this,
          Invocation.method(
            #saveWatchlist,
            [itemDataEntity],
          ),
        )),
      ) as _i9.Future<_i2.Either<_i10.Failure, String>>);

  @override
  _i9.Future<_i2.Either<_i10.Failure, String>> removeWatchlist(
    int? id,
    int? dataType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeWatchlist,
          [
            id,
            dataType,
          ],
        ),
        returnValue: _i9.Future<_i2.Either<_i10.Failure, String>>.value(
            _FakeEither_0<_i10.Failure, String>(
          this,
          Invocation.method(
            #removeWatchlist,
            [
              id,
              dataType,
            ],
          ),
        )),
      ) as _i9.Future<_i2.Either<_i10.Failure, String>>);

  @override
  _i9.Future<bool> isAddedToWatchlist(
    int? id,
    int? dataType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isAddedToWatchlist,
          [
            id,
            dataType,
          ],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<_i2.Either<_i10.Failure, List<_i20.Poster5Entity>>>
      getWatchlist() => (super.noSuchMethod(
            Invocation.method(
              #getWatchlist,
              [],
            ),
            returnValue: _i9.Future<
                    _i2.Either<_i10.Failure, List<_i20.Poster5Entity>>>.value(
                _FakeEither_0<_i10.Failure, List<_i20.Poster5Entity>>(
              this,
              Invocation.method(
                #getWatchlist,
                [],
              ),
            )),
          ) as _i9.Future<_i2.Either<_i10.Failure, List<_i20.Poster5Entity>>>);
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i21.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i22.Database?> get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _i9.Future<_i22.Database?>.value(),
      ) as _i9.Future<_i22.Database?>);

  @override
  _i9.Future<int> insertWatchlist(_i16.WatchlistTable? movie) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertWatchlist,
          [movie],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<int> removeWatchlist(
    int? id,
    int? dataType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeWatchlist,
          [
            id,
            dataType,
          ],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<Map<String, dynamic>?> getMovieById(
    int? id,
    int? dataType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieById,
          [
            id,
            dataType,
          ],
        ),
        returnValue: _i9.Future<Map<String, dynamic>?>.value(),
      ) as _i9.Future<Map<String, dynamic>?>);

  @override
  _i9.Future<List<Map<String, dynamic>>> getWatchlistMovies() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWatchlistMovies,
          [],
        ),
        returnValue: _i9.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i9.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [TvRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvRemoteDataSource extends _i1.Mock
    implements _i23.TvRemoteDataSource {
  MockTvRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<List<_i24.ResultTvSeries>> getPopularTvSeries() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPopularTvSeries,
          [],
        ),
        returnValue: _i9.Future<List<_i24.ResultTvSeries>>.value(
            <_i24.ResultTvSeries>[]),
      ) as _i9.Future<List<_i24.ResultTvSeries>>);

  @override
  _i9.Future<List<_i24.ResultTvSeries>> getOnTheAirTvSeries() =>
      (super.noSuchMethod(
        Invocation.method(
          #getOnTheAirTvSeries,
          [],
        ),
        returnValue: _i9.Future<List<_i24.ResultTvSeries>>.value(
            <_i24.ResultTvSeries>[]),
      ) as _i9.Future<List<_i24.ResultTvSeries>>);

  @override
  _i9.Future<List<_i24.ResultTvSeries>> getTopRatedTvSeries() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopRatedTvSeries,
          [],
        ),
        returnValue: _i9.Future<List<_i24.ResultTvSeries>>.value(
            <_i24.ResultTvSeries>[]),
      ) as _i9.Future<List<_i24.ResultTvSeries>>);

  @override
  _i9.Future<List<_i24.ResultTvSeries>> searchTvSeries(String? keyword) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchTvSeries,
          [keyword],
        ),
        returnValue: _i9.Future<List<_i24.ResultTvSeries>>.value(
            <_i24.ResultTvSeries>[]),
      ) as _i9.Future<List<_i24.ResultTvSeries>>);

  @override
  _i9.Future<_i4.TvDetailResponseModel> getTvSeriesDetail(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvSeriesDetail,
          [id],
        ),
        returnValue: _i9.Future<_i4.TvDetailResponseModel>.value(
            _FakeTvDetailResponseModel_2(
          this,
          Invocation.method(
            #getTvSeriesDetail,
            [id],
          ),
        )),
      ) as _i9.Future<_i4.TvDetailResponseModel>);

  @override
  _i9.Future<List<_i24.ResultTvSeries>> getTvSeriesRecommendation(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvSeriesRecommendation,
          [id],
        ),
        returnValue: _i9.Future<List<_i24.ResultTvSeries>>.value(
            <_i24.ResultTvSeries>[]),
      ) as _i9.Future<List<_i24.ResultTvSeries>>);
}

/// A class which mocks [TvSeriesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesRepository extends _i1.Mock
    implements _i25.TvSeriesRepository {
  MockTvSeriesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i2.Either<_i10.Failure, List<_i26.TvSeriesEntity>>>
      getOnTheAirTvSeries() => (super.noSuchMethod(
            Invocation.method(
              #getOnTheAirTvSeries,
              [],
            ),
            returnValue: _i9.Future<
                    _i2.Either<_i10.Failure, List<_i26.TvSeriesEntity>>>.value(
                _FakeEither_0<_i10.Failure, List<_i26.TvSeriesEntity>>(
              this,
              Invocation.method(
                #getOnTheAirTvSeries,
                [],
              ),
            )),
          ) as _i9.Future<_i2.Either<_i10.Failure, List<_i26.TvSeriesEntity>>>);

  @override
  _i9.Future<_i2.Either<_i10.Failure, List<_i26.TvSeriesEntity>>>
      getPopularTvSeries() => (super.noSuchMethod(
            Invocation.method(
              #getPopularTvSeries,
              [],
            ),
            returnValue: _i9.Future<
                    _i2.Either<_i10.Failure, List<_i26.TvSeriesEntity>>>.value(
                _FakeEither_0<_i10.Failure, List<_i26.TvSeriesEntity>>(
              this,
              Invocation.method(
                #getPopularTvSeries,
                [],
              ),
            )),
          ) as _i9.Future<_i2.Either<_i10.Failure, List<_i26.TvSeriesEntity>>>);

  @override
  _i9.Future<_i2.Either<_i10.Failure, List<_i26.TvSeriesEntity>>>
      getTopRatedTvSeries() => (super.noSuchMethod(
            Invocation.method(
              #getTopRatedTvSeries,
              [],
            ),
            returnValue: _i9.Future<
                    _i2.Either<_i10.Failure, List<_i26.TvSeriesEntity>>>.value(
                _FakeEither_0<_i10.Failure, List<_i26.TvSeriesEntity>>(
              this,
              Invocation.method(
                #getTopRatedTvSeries,
                [],
              ),
            )),
          ) as _i9.Future<_i2.Either<_i10.Failure, List<_i26.TvSeriesEntity>>>);

  @override
  _i9.Future<_i2.Either<_i10.Failure, List<_i26.TvSeriesEntity>>>
      searchTvSeries(String? keyword) => (super.noSuchMethod(
            Invocation.method(
              #searchTvSeries,
              [keyword],
            ),
            returnValue: _i9.Future<
                    _i2.Either<_i10.Failure, List<_i26.TvSeriesEntity>>>.value(
                _FakeEither_0<_i10.Failure, List<_i26.TvSeriesEntity>>(
              this,
              Invocation.method(
                #searchTvSeries,
                [keyword],
              ),
            )),
          ) as _i9.Future<_i2.Either<_i10.Failure, List<_i26.TvSeriesEntity>>>);

  @override
  _i9.Future<_i2.Either<_i10.Failure, _i19.ItemDataEntity>> getTvSeriesDetail(
          int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvSeriesDetail,
          [id],
        ),
        returnValue:
            _i9.Future<_i2.Either<_i10.Failure, _i19.ItemDataEntity>>.value(
                _FakeEither_0<_i10.Failure, _i19.ItemDataEntity>(
          this,
          Invocation.method(
            #getTvSeriesDetail,
            [id],
          ),
        )),
      ) as _i9.Future<_i2.Either<_i10.Failure, _i19.ItemDataEntity>>);

  @override
  _i9.Future<_i2.Either<_i10.Failure, List<_i26.TvSeriesEntity>>>
      getTvSeriesRecommendation(int? id) => (super.noSuchMethod(
            Invocation.method(
              #getTvSeriesRecommendation,
              [id],
            ),
            returnValue: _i9.Future<
                    _i2.Either<_i10.Failure, List<_i26.TvSeriesEntity>>>.value(
                _FakeEither_0<_i10.Failure, List<_i26.TvSeriesEntity>>(
              this,
              Invocation.method(
                #getTvSeriesRecommendation,
                [id],
              ),
            )),
          ) as _i9.Future<_i2.Either<_i10.Failure, List<_i26.TvSeriesEntity>>>);
}

/// A class which mocks [FirebaseAnalyticsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseAnalyticsService extends _i1.Mock
    implements _i27.FirebaseAnalyticsService {
  MockFirebaseAnalyticsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.FirebaseAnalytics get analytics => (super.noSuchMethod(
        Invocation.getter(#analytics),
        returnValue: _FakeFirebaseAnalytics_3(
          this,
          Invocation.getter(#analytics),
        ),
      ) as _i5.FirebaseAnalytics);

  @override
  _i5.FirebaseAnalyticsObserver initAnalytics() => (super.noSuchMethod(
        Invocation.method(
          #initAnalytics,
          [],
        ),
        returnValue: _FakeFirebaseAnalyticsObserver_4(
          this,
          Invocation.method(
            #initAnalytics,
            [],
          ),
        ),
      ) as _i5.FirebaseAnalyticsObserver);

  @override
  void setMessage(String? message) => super.noSuchMethod(
        Invocation.method(
          #setMessage,
          [message],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<void> setDefaultEventParameters() => (super.noSuchMethod(
        Invocation.method(
          #setDefaultEventParameters,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> sendAnalyticsEvent(
    String? event,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendAnalyticsEvent,
          [
            event,
            data,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> testSetUserId() => (super.noSuchMethod(
        Invocation.method(
          #testSetUserId,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> testSetCurrentScreen() => (super.noSuchMethod(
        Invocation.method(
          #testSetCurrentScreen,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> testSetAnalyticsCollectionEnabled() => (super.noSuchMethod(
        Invocation.method(
          #testSetAnalyticsCollectionEnabled,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> testSetSessionTimeoutDuration() => (super.noSuchMethod(
        Invocation.method(
          #testSetSessionTimeoutDuration,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> testSetUserProperty() => (super.noSuchMethod(
        Invocation.method(
          #testSetUserProperty,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> testAppInstanceId() => (super.noSuchMethod(
        Invocation.method(
          #testAppInstanceId,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> testResetAnalyticsData() => (super.noSuchMethod(
        Invocation.method(
          #testResetAnalyticsData,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i5.AnalyticsEventItem itemCreator() => (super.noSuchMethod(
        Invocation.method(
          #itemCreator,
          [],
        ),
        returnValue: _FakeAnalyticsEventItem_5(
          this,
          Invocation.method(
            #itemCreator,
            [],
          ),
        ),
      ) as _i5.AnalyticsEventItem);

  @override
  _i9.Future<void> testAllEventTypes() => (super.noSuchMethod(
        Invocation.method(
          #testAllEventTypes,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
}

/// A class which mocks [HttpCustomClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i28.HttpCustomClient {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i29.IOClient?> get ioClient => (super.noSuchMethod(
        Invocation.getter(#ioClient),
        returnValue: _i9.Future<_i29.IOClient?>.value(),
      ) as _i9.Future<_i29.IOClient?>);

  @override
  _i9.Future<_i6.SecurityContext> get globalContext => (super.noSuchMethod(
        Invocation.getter(#globalContext),
        returnValue:
            _i9.Future<_i6.SecurityContext>.value(_FakeSecurityContext_6(
          this,
          Invocation.getter(#globalContext),
        )),
      ) as _i9.Future<_i6.SecurityContext>);

  @override
  _i9.Future<_i7.Response> get(Uri? url) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
        ),
        returnValue: _i9.Future<_i7.Response>.value(_FakeResponse_7(
          this,
          Invocation.method(
            #get,
            [url],
          ),
        )),
      ) as _i9.Future<_i7.Response>);
}
